// <auto-generated />
namespace A1TopicosIII.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Remocao_cidade_estado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remocao_cidade_estado));
        
        string IMigrationMetadata.Id
        {
            get { return "202209280106366_Remocao_cidade_estado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
