// <auto-generated />
namespace A1TopicosIII.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class correcao_empresa_resonsavel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correcao_empresa_resonsavel));
        
        string IMigrationMetadata.Id
        {
            get { return "202210022057436_correcao_empresa_resonsavel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
