// <auto-generated />
namespace A1TopicosIII.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adicao_responsavel_contrato : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicao_responsavel_contrato));
        
        string IMigrationMetadata.Id
        {
            get { return "202209290120596_adicao_responsavel_contrato"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
