// <auto-generated />
namespace A1TopicosIII.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class remocao_fax_email : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remocao_fax_email));
        
        string IMigrationMetadata.Id
        {
            get { return "202209280113451_remocao_fax_email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
