{
 "title": "Adonis Metrics",
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"adonis_metrics\"}[1m])",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Response Duration",
   "type": "graph",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"adonis_metrics\"}[5m])) by (le, method, route))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "table",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "up{job=\"adonis_metrics\"}"
    }
   ]
  }
 ]
}